#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Speaker-identity check for prefill-graph on/off.

WER answers "are the words right"; this answers "is it the same voice". Compares
x-vectors of the *same prompt* generated by two runs, so the eager-vs-eager pair
is the control for natural run-to-run variation.
"""

from __future__ import annotations

import os
import sys
import wave

import numpy as np
import torch
from transformers import AutoFeatureExtractor, WavLMForXVector

MODEL = "microsoft/wavlm-base-plus-sv"


def load16k(path: str) -> np.ndarray:
    with wave.open(path, "rb") as w:
        sr = w.getframerate()
        x = np.frombuffer(w.readframes(w.getnframes()), dtype=np.int16).astype(np.float32)
        ch = w.getnchannels()
    if ch > 1:
        x = x.reshape(-1, ch).mean(axis=1)
    x = x / 32768.0
    if sr != 16000:
        idx = np.round(np.arange(0, len(x), sr / 16000.0)).astype(int)
        x = x[idx[idx < len(x)]]
    return x


def xvectors(paths, fe, model):
    out = []
    for i in range(0, len(paths), 8):
        batch = [load16k(p) for p in paths[i : i + 8]]
        inp = fe(batch, sampling_rate=16000, return_tensors="pt", padding=True)
        inp = {k: v.to("cuda:0") for k, v in inp.items()}
        with torch.no_grad():
            e = model(**inp).embeddings
        out.append(torch.nn.functional.normalize(e, dim=-1).cpu())
    return torch.cat(out)


def pair(a_dir, b_dir, fe, model, label):
    pa, pb = os.path.join(a_dir, "audio"), os.path.join(b_dir, "audio")
    common = sorted(set(os.listdir(pa)) & set(os.listdir(pb)))
    ea = xvectors([os.path.join(pa, f) for f in common], fe, model)
    eb = xvectors([os.path.join(pb, f) for f in common], fe, model)
    cos = (ea * eb).sum(-1).numpy()
    print(
        "%-34s median=%.4f  mean=%.4f  min=%.4f  n=%d"
        % (label, float(np.median(cos)), float(cos.mean()), float(cos.min()), len(common)),
        flush=True,
    )


if __name__ == "__main__":
    fe = AutoFeatureExtractor.from_pretrained(MODEL)
    model = WavLMForXVector.from_pretrained(MODEL).to("cuda:0").eval()
    base = sys.argv[1] if len(sys.argv) > 1 else "."
    j = lambda d: os.path.join(base, d)
    pair(j("G3BASE-b1-c1"), j("G3BASE-b2-c1"), fe, model, "CONTROL eager vs eager")
    pair(j("G3FIX-b1-c1"), j("G3FIX-b2-c1"), fe, model, "CONTROL graph vs graph")
    pair(j("G3BASE-b1-c1"), j("G3FIX-b1-c1"), fe, model, "TEST    eager vs graph (b1)")
    pair(j("G3BASE-b2-c1"), j("G3FIX-b2-c1"), fe, model, "TEST    eager vs graph (b2)")
